@startuml

title __SETTINGS's Class Diagram__\n

  namespace com.example.thetrempiada {
    namespace ui.settings {
      class com.example.thetrempiada.ui.settings.ProfileSettingsActivity {
          {static} - GENDER_PATHS : String[]
          - PICK_IMAGE_REQUEST : int
          {static} - TYPE_PATHS : String[]
          - alrClickedConfirm : boolean
          - confirmChanges : Button
          - confirmPassword : TextInputEditText
          - confirmPasswordValid : boolean
          - currentUser : FirebaseUser
          - databaseReference : DatabaseReference
          - displayNameValid : boolean
          - editAge : TextInputEditText
          - editDescription : TextInputEditText
          - editDisplayName : TextInputEditText
          - editGender : AutoCompleteTextView
          - editProfilePicture : ImageView
          - editProfileTitle : TextView
          - editUserType : AutoCompleteTextView
          {static} - filePath : Uri
          - genderSelected : boolean
          - nameContainer : TextInputLayout
          - passwordContainer : TextInputLayout
          - progressBar : ProgressBar
          {static} - storageReference : StorageReference
          - userTypeSelected : boolean
          + onBackPressed()
          + onCreateOptionsMenu()
          + onOptionsItemSelected()
          # onActivityResult()
          # onCreate()
      }
    }
  }
  

  namespace com.example.thetrempiada {
    namespace ui.settings {
      class com.example.thetrempiada.ui.settings.SettingsActivity {
          - alrClickedChangeEmail : boolean
          - alrClickedChangePassword : boolean
          - alrClickedDeleteUser : boolean
          - changeEmail : Button
          - changePassword : Button
          - confirmPasswordValid : boolean
          - deleteUser : Button
          - editProfile : Button
          - intent : Intent
          - mapSettingsTitle : TextView
          - newEmailValid : boolean
          - newPasswordValid : boolean
          - nightModeSwitch : SwitchMaterial
          - oldPasswordValid : boolean
          - passwordValid : boolean
          - profileSettingsTitle : TextView
          - satelliteSwitch : SwitchMaterial
          - user : FirebaseUser
          + editSwitchPreferences()
          + onBackPressed()
          + onCreateOptionsMenu()
          + onOptionsItemSelected()
          # onCreate()
      }
    }
  }
  

  com.example.thetrempiada.ui.settings.ProfileSettingsActivity -up-|> com.example.thetrempiada.data.BaseActivity
  com.example.thetrempiada.ui.settings.SettingsActivity -up-|> com.example.thetrempiada.data.BaseActivity


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
