@startuml

title __THETREMPIADA's Class Diagram__\n

  namespace com.example.thetrempiada {
    class com.example.thetrempiada.MainActivity {
        {static} + MY_PERMISSIONS_REQUEST_LOCATION : int
        {static} + activePolylines : List<Polyline>
        {static} + destinationOfDriveMarker : Marker
        {static} + mCurLatLng : LatLng
        {static} + mGoogleMap : GoogleMap
        {static} + openedMarker : Marker
        ~ mLocationCallback : LocationCallback
        {static} - AUTOCOMPLETE_REQUEST_CODE_NEW_DRIVE : int
        {static} - AUTOCOMPLETE_REQUEST_CODE_TAKE_TREMP : int
        - MAP_TYPE_NIGHT : int
        - cardDescription : TextView
        - cardMessageBtn : Button
        - cardProfilePicture : ImageView
        - cardSecondary : TextView
        - cardTakeTrempBtn : Button
        - cardTitle : TextView
        - fireAuthListener : AuthStateListener
        - firebaseAuth : FirebaseAuth
        - mAppBarConfiguration : AppBarConfiguration
        - mCurrLocationMarker : Marker
        - mFusedLocationClient : FusedLocationProviderClient
        - mLocationRequest : LocationRequest
        - mainMenu : Menu
        - mainSharedPref : SharedPreferences
        - mapFragment : SupportMapFragment
        - mapType : int
        - userProfileCardView : MaterialCardView
        - zoomedIn : boolean
        + distanceInKilometers()
        + drawGeoPolyline()
        + onCreateOptionsMenu()
        + onMapReady()
        + onOptionsItemSelected()
        + onRequestPermissionsResult()
        + onSupportNavigateUp()
        + saveMapTypeToPreference()
        # onActivityResult()
        # onCreate()
        # onPause()
        # onStart()
        # onStop()
        - checkLocationPermission()
    }
  }
  

  com.example.thetrempiada.MainActivity .up.|> com.google.android.gms.maps.OnMapReadyCallback
  com.example.thetrempiada.MainActivity -up-|> com.example.thetrempiada.data.BaseActivity


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
